# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd BarkingCat
        sudo ./gradlew build
    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: tr330ak/demo-app
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
      
#  deploy:
#    needs: CI
#    name: Deploy
#    runs-on: [ self-hosted ]
#    steps:
#      - name: Login to Docker
#        uses: docker/login-action@v1
#        with:
#          registry: docker.io
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Docker run
#        run: |
#          docker stop barking-cat && docker rm -fv barking-cat
#          docker rmi -f rkdals213/barking-cat
#          docker run -d -p 8080:8080 --name barking-cat --restart always rkdals213/barking-cat:latest
